title: jooooh's blog
url: http://jooooh.github.io
encoding: utf-8

name: Jungju Oh

# Configuration
plugins:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
mathjax: true

nav:
  Home:
    - '/'
  Contents:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'
